### ISSUE TITLE
Custom style not loading

### ISSUE THREAD

**Issue by steveddan** [JoseLuisGJ/figmap#8]
When I enter my username and style ID for a custom style, the map turns blank. I am wondering if my access token is additionally needed to get the custom style to load. 

<img width="816" alt="image" src="https://github.com/JoseLuisGJ/figmap/assets/92470017/5b40be3a-aff7-4cf4-a572-d189ce7e487a">

Thanks for your help!

**Comment by craftycram** [comment]
can confirm. got the same issue

**Comment by craftycram** [comment]
Further update. I get a 404 Not Found response from mapbox in the console

**Comment by craftycram** [comment]
Another update. I tried copying the request from the console and just replace your access token with mine that worked.  
Forking and replacing your access token with mine in code and loading that plugin also worked.  
Seems like your access token seems to be the issue.  
Maybe change the token or give users the option to provide their own it else is too expensive for you

**Comment by JoseLuisGJ** [comment]
Thanks for the feedback @steveddan and @craftycram it's something that I tried to manage in the past without success. Seems that the react Mapbox library I'm using doesn't update the Mapbox API token. I already opened an issue [here](https://github.com/visgl/react-map-gl/issues/2340) hopping to solve it once I get an answer.

**Comment by Simo-DA** [comment]
Same problem here...

**Comment by JoseLuisGJ** [comment]
Thanks for your patience @steveddan @craftycram and @Simo-DA . I recently published a new version and I made some tests and it's working for me. Can you check it again? thanks.

**Comment by craftycram** [comment]
<img width="549" alt="grafik" src="https://github.com/JoseLuisGJ/figmap/assets/32396733/7367dcc8-8a54-448e-b630-e9077daaa554">
still getting a 404 error… not sure why tho

**Comment by craftycram** [comment]
After lookin into it I still think that the access token could be the issue. Taking the request figmap does and replacing your access token with mine resolves the issue.  
Maybe change the input fields of figmap to style url and access token?

Just like you can copy here:  
<img width="195" alt="grafik" src="https://github.com/JoseLuisGJ/figmap/assets/32396733/e3f9bb5e-ad1b-4972-837f-5ac49eae3f4f">

**Comment by craftycram** [comment]
Like mentioned before I'm using a forked version of FigMap where I just replaced the access token to make it work. Having no issues at all.

**Comment by JoseLuisGJ** [comment]
@craftycram did you check wether your map style was published and public available? I created 2 temp accounts in Mapbox to try it out one more time. And it's easy to believe that your map style is public but by default it's not and when it's not public is when you get this 404 error fetching this data with a token not scoped for that style.

Makes sense if you can see your style changing also the Mapbox access token forking the repo due to this token scopes the styles you own for that account.

Please make sure you press the **Make public** button your Mapbox styles in Mapbox Studio here and try again:

![CleanShot 2024-07-08 at 09 26 13@2x](https://github.com/JoseLuisGJ/figmap/assets/3108788/dc5f8090-2ba9-44b9-8631-d5ba67499dd6)

**Comment by Simo-DA** [comment]
@JoseLuisGJ thanks a lot for your fast response. I think in my case the style is also not loading, cause the map style is not public.
 
Unfortunately I can not test it, since I am getting a network error in Mapbox Studio when I try to do so...

**Comment by JoseLuisGJ** [comment]
I brought back the _Mapbox API access token_ field to the plugin. With that you can now use your own token and consume private maps styles as you suggested. Managing that one is not trivial, the Mapbox token is not a reactive prop. Now the map component is re-rendered every time a new token is provided.

I'm still trying to [improve the validation](https://github.com/visgl/react-map-gl/discussions/2414) of the token provided in order to prevent the plugin crash. But for now is quite stable with valid tokens and store the data for the following plugin runs.

![CleanShot 2024-07-10 at 13 09 06@2x](https://github.com/JoseLuisGJ/figmap/assets/3108788/0e54a413-c9d4-4ab7-bd3f-8a8c1087e0f7)

**Comment by craftycram** [comment]
sorry, somehow missed the notification.  
yea I did try with public and private styles, somehow both didn't seem to work.  
but now that we got a api token field that issue shouldn't be a problem anymore.  
thanks for the implementation, gonna let my students know that they can use the plugin again 😌
